// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJUS2QXCKaLl0bt4-Zr9a84NGq6vYtRfA',
    appId: '1:49581970803:web:e3e3e9a426c09f34bbe106',
    messagingSenderId: '49581970803',
    projectId: 'translateapp-bd410',
    authDomain: 'translateapp-bd410.firebaseapp.com',
    storageBucket: 'translateapp-bd410.firebasestorage.app',
    measurementId: 'G-9FCMD2HYYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9rW3S5x8zbmjcWkSCbGkVJd4NKIMbBc',
    appId: '1:49581970803:android:b2768ebbdcd196fcbbe106',
    messagingSenderId: '49581970803',
    projectId: 'translateapp-bd410',
    storageBucket: 'translateapp-bd410.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ1vRV6-hvE0vXTyVUVfko1wZ7nEiW3eQ',
    appId: '1:49581970803:ios:fde51d64e314b713bbe106',
    messagingSenderId: '49581970803',
    projectId: 'translateapp-bd410',
    storageBucket: 'translateapp-bd410.firebasestorage.app',
    androidClientId: '49581970803-fags810ht6c9v4m1hlffr3vl297sotl8.apps.googleusercontent.com',
    iosClientId: '49581970803-45o3glc92a4kp9hok6ulcak0dfj55lim.apps.googleusercontent.com',
    iosBundleId: 'com.example.translateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ1vRV6-hvE0vXTyVUVfko1wZ7nEiW3eQ',
    appId: '1:49581970803:ios:fde51d64e314b713bbe106',
    messagingSenderId: '49581970803',
    projectId: 'translateapp-bd410',
    storageBucket: 'translateapp-bd410.firebasestorage.app',
    androidClientId: '49581970803-fags810ht6c9v4m1hlffr3vl297sotl8.apps.googleusercontent.com',
    iosClientId: '49581970803-45o3glc92a4kp9hok6ulcak0dfj55lim.apps.googleusercontent.com',
    iosBundleId: 'com.example.translateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJUS2QXCKaLl0bt4-Zr9a84NGq6vYtRfA',
    appId: '1:49581970803:web:eb64dbd5158bbf6bbbe106',
    messagingSenderId: '49581970803',
    projectId: 'translateapp-bd410',
    authDomain: 'translateapp-bd410.firebaseapp.com',
    storageBucket: 'translateapp-bd410.firebasestorage.app',
    measurementId: 'G-E7KE0DHSK9',
  );
}
